environments:
  ts_dr_deploy:
    environment_variables:
      NeoVerboseLogging: "false"
      NeoDebugLogging: "false"
      NeoPsVersion: "1.2.135"
      AZURE_TENANT_ID: "c9871c9d-7fe6-4b1d-a97a-22b172b872e7"
      GitHubToken: "{{SECRET:[singular-secrets][singular-github-readonly-token]}}"
      GitHubRepository: ""
      GitHubRepositoryDeployBranch: "main"
      AZURE_SUBSCRIPTION_ID: "aa7782d9-0b79-4740-9750-caf85a5aba67"
      AZURE_CLIENT_ID: "{{SECRET:[custom-secrets-sc-dr][sc-dr-sp-operations-app-id]}}"
      AZURE_CLIENT_SECRET: "{{SECRET:[custom-secrets-sc-dr][sc-dr-sp-operations-secret]}}"
    agents:
      # ZeroTrust01 - ZeroTrust08
      - e31184ff-0dca-46fd-a917-11218a3cd840
      - da6ff6f6-a8a0-48c7-b71a-9ec1c2b8628d
      - 5ebf84ba-c240-4980-bf44-883cb6c4d5a8
      - 4ee24cb8-9645-4a9d-a115-91856d194d23
      - 834f8c54-2fa7-4a0e-9419-b9b1829d411c
      - 3035c8f9-6650-46e7-93b8-1820c4749c2a
      - 792d8d0b-525f-4c03-88a5-1859c6299272
      - ddbb9e66-2fcd-4c37-bcd9-715e8efa9c77
    pipelines:
      - ts_deploy_ci_dr_domain
      - ts_deploy_ci_dr_identity_server
      - ts_deploy_ci_dr_web_app
      - ts_deploy_hotfix_dr_domain
      - ts_deploy_hotfix_dr_identity_server
      - ts_deploy_hotfix_dr_web_app

  ts_pp_deploy:
    environment_variables:
      NeoVerboseLogging: "false"
      NeoDebugLogging: "false"
      NeoPsVersion: "1.2.135"
      AZURE_TENANT_ID: "c9871c9d-7fe6-4b1d-a97a-22b172b872e7"
      GitHubToken: "{{SECRET:[singular-secrets][singular-github-readonly-token]}}"
      GitHubRepository: ""
      GitHubRepositoryDeployBranch: "main"
      AZURE_SUBSCRIPTION_ID: "aa7782d9-0b79-4740-9750-caf85a5aba67"
      AZURE_CLIENT_ID: "{{SECRET:[custom-secrets-sc-prd][sc-prd-sp-operations-app-id]}}"
      AZURE_CLIENT_SECRET: "{{SECRET:[custom-secrets-sc-prd][sc-prd-sp-operations-secret]}}"
    agents:
      # ZeroTrust01 - ZeroTrust08
      - e31184ff-0dca-46fd-a917-11218a3cd840
      - da6ff6f6-a8a0-48c7-b71a-9ec1c2b8628d
      - 5ebf84ba-c240-4980-bf44-883cb6c4d5a8
      - 4ee24cb8-9645-4a9d-a115-91856d194d23
      - 834f8c54-2fa7-4a0e-9419-b9b1829d411c
      - 3035c8f9-6650-46e7-93b8-1820c4749c2a
      - 792d8d0b-525f-4c03-88a5-1859c6299272
      - ddbb9e66-2fcd-4c37-bcd9-715e8efa9c77
    pipelines:
      - ts_deploy_ci_pp_domain
      - ts_deploy_ci_pp_identity_server
      - ts_deploy_ci_pp_web_app
      - ts_deploy_hotfix_pp_domain
      - ts_deploy_hotfix_pp_identity_server
      - ts_deploy_hotfix_pp_web_app

  ts_prd_deploy:
    environment_variables:
      NeoVerboseLogging: "false"
      NeoDebugLogging: "false"
      NeoPsVersion: "1.2.135"
      AZURE_TENANT_ID: "c9871c9d-7fe6-4b1d-a97a-22b172b872e7"
      GitHubToken: "{{SECRET:[singular-secrets][singular-github-readonly-token]}}"
      GitHubRepository: ""
      GitHubRepositoryDeployBranch: "main"
      AZURE_SUBSCRIPTION_ID: "aa7782d9-0b79-4740-9750-caf85a5aba67"
      AZURE_CLIENT_ID: "{{SECRET:[custom-secrets-sc-prd][sc-prd-sp-operations-app-id]}}"
      AZURE_CLIENT_SECRET: "{{SECRET:[custom-secrets-sc-prd][sc-prd-sp-operations-secret]}}"
    agents:
      # ZeroTrust01 - ZeroTrust08
      - e31184ff-0dca-46fd-a917-11218a3cd840
      - da6ff6f6-a8a0-48c7-b71a-9ec1c2b8628d
      - 5ebf84ba-c240-4980-bf44-883cb6c4d5a8
      - 4ee24cb8-9645-4a9d-a115-91856d194d23
      - 834f8c54-2fa7-4a0e-9419-b9b1829d411c
      - 3035c8f9-6650-46e7-93b8-1820c4749c2a
      - 792d8d0b-525f-4c03-88a5-1859c6299272
      - ddbb9e66-2fcd-4c37-bcd9-715e8efa9c77
    pipelines:
      - ts_deploy_ci_prd_domain
      - ts_deploy_ci_prd_identity_server
      - ts_deploy_ci_prd_web_app
      - ts_deploy_hotfix_prd_domain
      - ts_deploy_hotfix_prd_identity_server
      - ts_deploy_hotfix_prd_web_app

  ts_qa_deploy:
    environment_variables:
      NeoVerboseLogging: "false"
      NeoDebugLogging: "false"
      NeoPsVersion: "1.2.135"
      AZURE_TENANT_ID: "c9871c9d-7fe6-4b1d-a97a-22b172b872e7"
      GitHubToken: "{{SECRET:[singular-secrets][singular-github-readonly-token]}}"
      GitHubRepository: ""
      GitHubRepositoryDeployBranch: "main"
      AZURE_SUBSCRIPTION_ID: "2e538ecd-e2f2-40d9-bc8a-272df8f5e2f7"
      AZURE_CLIENT_ID: "{{SECRET:[custom-secrets-sc-stg][sc-stg-sp-operations-app-id]}}"
      AZURE_CLIENT_SECRET: "{{SECRET:[custom-secrets-sc-stg][sc-stg-sp-operations-secret]}}"
    agents:
      # ZeroTrust01 - ZeroTrust08
      - e31184ff-0dca-46fd-a917-11218a3cd840
      - da6ff6f6-a8a0-48c7-b71a-9ec1c2b8628d
      - 5ebf84ba-c240-4980-bf44-883cb6c4d5a8
      - 4ee24cb8-9645-4a9d-a115-91856d194d23
      - 834f8c54-2fa7-4a0e-9419-b9b1829d411c
      - 3035c8f9-6650-46e7-93b8-1820c4749c2a
      - 792d8d0b-525f-4c03-88a5-1859c6299272
      - ddbb9e66-2fcd-4c37-bcd9-715e8efa9c77
    pipelines:
      - ts_deploy_ci_qa_domain
      - ts_deploy_ci_qa_identity_server
      - ts_deploy_ci_qa_web_app

  ts_uat_deploy:
    environment_variables:
      NeoVerboseLogging: "false"
      NeoDebugLogging: "false"
      NeoPsVersion: "1.2.135"
      AZURE_TENANT_ID: "c9871c9d-7fe6-4b1d-a97a-22b172b872e7"
      GitHubToken: "{{SECRET:[singular-secrets][singular-github-readonly-token]}}"
      GitHubRepository: ""
      GitHubRepositoryDeployBranch: "main"
      AZURE_SUBSCRIPTION_ID: "2e538ecd-e2f2-40d9-bc8a-272df8f5e2f7"
      AZURE_CLIENT_ID: "{{SECRET:[custom-secrets-sc-stg][sc-stg-sp-operations-app-id]}}"
      AZURE_CLIENT_SECRET: "{{SECRET:[custom-secrets-sc-stg][sc-stg-sp-operations-secret]}}"
    agents:
      # ZeroTrust01 - ZeroTrust08
      - e31184ff-0dca-46fd-a917-11218a3cd840
      - da6ff6f6-a8a0-48c7-b71a-9ec1c2b8628d
      - 5ebf84ba-c240-4980-bf44-883cb6c4d5a8
      - 4ee24cb8-9645-4a9d-a115-91856d194d23
      - 834f8c54-2fa7-4a0e-9419-b9b1829d411c
      - 3035c8f9-6650-46e7-93b8-1820c4749c2a
      - 792d8d0b-525f-4c03-88a5-1859c6299272
      - ddbb9e66-2fcd-4c37-bcd9-715e8efa9c77
    pipelines:
      - ts_deploy_ci_uat_domain
      - ts_deploy_ci_uat_identity_server
      - ts_deploy_ci_uat_web_app
