// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuckshop.AuthorisationServer.Models;

#nullable disable

namespace Tuckshop.AuthorisationServer.Models.Migrations.Migrations
{
    [DbContext(typeof(AuthorisationDbContext))]
    partial class AuthorisationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Audit_UserGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeAction")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ChangedBy")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ChangedByGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ChangedOn")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsAdministratorGroup")
                        .HasColumnType("bit");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<string>("UserGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserGroupId");

                    b.ToTable("Audit_UserGroups", (string)null);
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.AssignedRole", b =>
                {
                    b.Property<int>("AssignedRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssignedRoleId"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.HasKey("AssignedRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserGroupId", "RoleId")
                        .IsUnique()
                        .HasFilter("Deleted_On IS NULL");

                    b.ToTable("AssignedRoles");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.Membership", b =>
                {
                    b.Property<int>("MembershipId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MembershipId"));

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserGroupId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("MembershipId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserGroupId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserGroupId", "UserId")
                        .IsUnique()
                        .HasFilter("Deleted_On IS NULL");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.Registration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RegistrationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("UserId");

                    b.HasIndex("TenantId", "UserId")
                        .IsUnique();

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.Resource", b =>
                {
                    b.Property<int>("ResourceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResourceId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Hash")
                        .HasColumnType("int");

                    b.Property<string>("ResourceName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ResourceId");

                    b.HasIndex("DeletedOn")
                        .HasFilter("DeletedOn IS NULL");

                    b.HasIndex("ResourceName")
                        .IsUnique()
                        .HasFilter("DeletedOn IS NULL");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("RoleCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("RoleDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("DeletedOn")
                        .HasFilter("DeletedOn IS NULL");

                    b.HasIndex("RoleCategoryId", "RoleName")
                        .IsUnique()
                        .HasFilter("DeletedOn IS NULL");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.RoleCategory", b =>
                {
                    b.Property<int>("RoleCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleCategoryId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DeletedOn")
                        .HasColumnType("datetime");

                    b.Property<int>("ResourceId")
                        .HasColumnType("int");

                    b.HasKey("RoleCategoryId");

                    b.HasIndex("DeletedOn")
                        .HasFilter("DeletedOn IS NULL");

                    b.HasIndex("ResourceId", "Category")
                        .IsUnique()
                        .HasFilter("DeletedOn IS NULL");

                    b.ToTable("RoleCategories");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.UserGroup", b =>
                {
                    b.Property<int>("UserGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserGroupId"));

                    b.Property<bool>("IsAdministratorGroup")
                        .HasColumnType("bit");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("UserGroupName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserGroupId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "UserGroupName")
                        .IsUnique()
                        .HasFilter("Deleted_On IS NULL");

                    b.ToTable("UserGroups");
                });

            modelBuilder.Entity("Tuckshop.AuthorisationServer.Models.TuckshopAuthorisationUser", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("IdentityGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsInvitedUser")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("PreferredName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UserName")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("UserId");

                    b.HasIndex("IdentityGuid", "ClientId")
                        .IsUnique()
                        .HasFilter("[IdentityGuid] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Audit_UserGroup", b =>
                {
                    b.OwnsOne("Neo.Model.ValueObjects.UserEvent", "Deleted", b1 =>
                        {
                            b1.Property<int>("Audit_UserGroupId")
                                .HasColumnType("int");

                            b1.Property<int?>("By")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("On")
                                .HasColumnType("datetime");

                            b1.HasKey("Audit_UserGroupId");

                            b1.ToTable("Audit_UserGroups");

                            b1.WithOwner()
                                .HasForeignKey("Audit_UserGroupId");
                        });

                    b.Navigation("Deleted");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.AssignedRole", b =>
                {
                    b.HasOne("Neo.AuthorisationServer.Models.Role", "Role")
                        .WithMany("Assignments")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Neo.AuthorisationServer.Models.UserGroup", "UserGroup")
                        .WithMany("AssignedRoles")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Neo.Model.ValueObjects.AuditValues", "Audit", b1 =>
                        {
                            b1.Property<int>("AssignedRoleId")
                                .HasColumnType("int");

                            b1.Property<int>("CreatedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime");

                            b1.Property<int>("ModifiedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ModifiedOn")
                                .HasColumnType("datetime");

                            b1.HasKey("AssignedRoleId");

                            b1.ToTable("AssignedRoles");

                            b1.WithOwner()
                                .HasForeignKey("AssignedRoleId");
                        });

                    b.OwnsOne("Neo.Model.ValueObjects.UserEvent", "Deleted", b1 =>
                        {
                            b1.Property<int>("AssignedRoleId")
                                .HasColumnType("int");

                            b1.Property<int?>("By")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("On")
                                .HasColumnType("datetime");

                            b1.HasKey("AssignedRoleId");

                            b1.HasIndex("On")
                                .HasFilter("Deleted_On IS NULL");

                            b1.ToTable("AssignedRoles");

                            b1.WithOwner()
                                .HasForeignKey("AssignedRoleId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Deleted")
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.Membership", b =>
                {
                    b.HasOne("Neo.AuthorisationServer.Models.UserGroup", "UserGroup")
                        .WithMany("Memberships")
                        .HasForeignKey("UserGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tuckshop.AuthorisationServer.Models.TuckshopAuthorisationUser", null)
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Neo.Model.ValueObjects.AuditValues", "Audit", b1 =>
                        {
                            b1.Property<int>("MembershipId")
                                .HasColumnType("int");

                            b1.Property<int>("CreatedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime");

                            b1.Property<int>("ModifiedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ModifiedOn")
                                .HasColumnType("datetime");

                            b1.HasKey("MembershipId");

                            b1.ToTable("Memberships");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.OwnsOne("Neo.Model.ValueObjects.UserEvent", "Deleted", b1 =>
                        {
                            b1.Property<int>("MembershipId")
                                .HasColumnType("int");

                            b1.Property<int?>("By")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("On")
                                .HasColumnType("datetime");

                            b1.HasKey("MembershipId");

                            b1.HasIndex("On")
                                .HasFilter("Deleted_On IS NULL");

                            b1.ToTable("Memberships");

                            b1.WithOwner()
                                .HasForeignKey("MembershipId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Deleted")
                        .IsRequired();

                    b.Navigation("UserGroup");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.Registration", b =>
                {
                    b.HasOne("Tuckshop.AuthorisationServer.Models.TuckshopAuthorisationUser", null)
                        .WithMany("Registrations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.Role", b =>
                {
                    b.HasOne("Neo.AuthorisationServer.Models.RoleCategory", "Category")
                        .WithMany("Roles")
                        .HasForeignKey("RoleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.RoleCategory", b =>
                {
                    b.HasOne("Neo.AuthorisationServer.Models.Resource", null)
                        .WithMany("RoleCategories")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.UserGroup", b =>
                {
                    b.OwnsOne("Neo.Model.ValueObjects.AuditValues", "Audit", b1 =>
                        {
                            b1.Property<int>("UserGroupId")
                                .HasColumnType("int");

                            b1.Property<int>("CreatedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime");

                            b1.Property<int>("ModifiedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ModifiedOn")
                                .HasColumnType("datetime");

                            b1.HasKey("UserGroupId");

                            b1.ToTable("UserGroups");

                            b1.WithOwner()
                                .HasForeignKey("UserGroupId");
                        });

                    b.OwnsOne("Neo.Model.ValueObjects.UserEvent", "Deleted", b1 =>
                        {
                            b1.Property<int>("UserGroupId")
                                .HasColumnType("int");

                            b1.Property<int?>("By")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("On")
                                .HasColumnType("datetime");

                            b1.HasKey("UserGroupId");

                            b1.HasIndex("On")
                                .HasFilter("Deleted_On IS NULL");

                            b1.ToTable("UserGroups");

                            b1.WithOwner()
                                .HasForeignKey("UserGroupId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Deleted")
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.Resource", b =>
                {
                    b.Navigation("RoleCategories");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.Role", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.RoleCategory", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Neo.AuthorisationServer.Models.UserGroup", b =>
                {
                    b.Navigation("AssignedRoles");

                    b.Navigation("Memberships");
                });

            modelBuilder.Entity("Tuckshop.AuthorisationServer.Models.TuckshopAuthorisationUser", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
