//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuckshop.IdentityServer.App.Notifications {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DefaultNotificationTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DefaultNotificationTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tuckshop.IdentityServer.App.Notifications.DefaultNotificationTemplates", typeof(DefaultNotificationTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear @Model.Recipient.DisplayName
        ///
        ///You have just registered on the Tuckshop online platform.
        ///To complete your registration, please verify your email by clicking  &lt;a href=&quot;@Model.VerificationUrl&quot;&gt;here&lt;/a&gt;.
        ///NOTE: This link will expire in @Model.LinkExpiryHours hours
        ///
        ///Kind Regards,
        ///Tuckshop.
        /// </summary>
        internal static string EmailVerification {
            get {
                return ResourceManager.GetString("EmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User
        ///
        ///You have just requested to reset your password on the Tuckshop platform.
        ///Please reset your password by &lt;a href=&quot;@Model.ResetLink&quot;&gt;clicking here&lt;/a&gt;.
        ///NOTE: This link will expire in @Model.LinkExpiryHours hours
        ///
        ///Kind Regards,
        ///Tuckshop.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have been invited to register on the Tuckshop platform.
        ///
        ///Please &lt;a href=&quot;@Model.RegistrationLink&quot;&gt;click here&lt;/a&gt; to register. .
        /// </summary>
        internal static string UserInvite {
            get {
                return ResourceManager.GetString("UserInvite", resourceCulture);
            }
        }
    }
}
