// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuckshop.Notifications;

#nullable disable

namespace Tuckshop.Notifications.Migrations.Migrations
{
    [DbContext(typeof(NotificationsDbContext))]
    partial class NotificationsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BulkNotificationStatusEntity", b =>
                {
                    b.Property<int>("BulkNotificationStatusId")
                        .HasColumnType("int");

                    b.Property<string>("BulkNotificationStatusName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BulkNotificationStatusId");

                    b.ToTable("BulkNotificationStatuses");

                    b.HasData(
                        new
                        {
                            BulkNotificationStatusId = 1,
                            BulkNotificationStatusName = "Pending"
                        },
                        new
                        {
                            BulkNotificationStatusId = 0,
                            BulkNotificationStatusName = "None"
                        },
                        new
                        {
                            BulkNotificationStatusId = 10,
                            BulkNotificationStatusName = "Ready"
                        },
                        new
                        {
                            BulkNotificationStatusId = 20,
                            BulkNotificationStatusName = "Scheduled"
                        },
                        new
                        {
                            BulkNotificationStatusId = 30,
                            BulkNotificationStatusName = "Processing"
                        },
                        new
                        {
                            BulkNotificationStatusId = 35,
                            BulkNotificationStatusName = "Sending"
                        },
                        new
                        {
                            BulkNotificationStatusId = 100,
                            BulkNotificationStatusName = "Completed"
                        },
                        new
                        {
                            BulkNotificationStatusId = 500,
                            BulkNotificationStatusName = "Failed Still Processing"
                        },
                        new
                        {
                            BulkNotificationStatusId = 501,
                            BulkNotificationStatusName = "Failed"
                        });
                });

            modelBuilder.Entity("DeliveryStatusEntity", b =>
                {
                    b.Property<int>("DeliveryStatusId")
                        .HasColumnType("int");

                    b.Property<string>("DeliveryStatusName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DeliveryStatusId");

                    b.ToTable("DeliveryStatuses");

                    b.HasData(
                        new
                        {
                            DeliveryStatusId = 1,
                            DeliveryStatusName = "Unsent"
                        },
                        new
                        {
                            DeliveryStatusId = 20,
                            DeliveryStatusName = "Queued"
                        },
                        new
                        {
                            DeliveryStatusId = 30,
                            DeliveryStatusName = "Sent"
                        },
                        new
                        {
                            DeliveryStatusId = 40,
                            DeliveryStatusName = "Delivered"
                        },
                        new
                        {
                            DeliveryStatusId = 50,
                            DeliveryStatusName = "Not Available"
                        },
                        new
                        {
                            DeliveryStatusId = 60,
                            DeliveryStatusName = "Failed"
                        },
                        new
                        {
                            DeliveryStatusId = 70,
                            DeliveryStatusName = "Ignored"
                        },
                        new
                        {
                            DeliveryStatusId = 71,
                            DeliveryStatusName = "Dont Send"
                        });
                });

            modelBuilder.Entity("Neo.BulkNotifications.Models.BulkNotification", b =>
                {
                    b.Property<int>("BulkNotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BulkNotificationId"));

                    b.Property<int>("BulkNotificationTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2(7)");

                    b.Property<string>("FailedReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("BulkNotificationId");

                    b.HasIndex("BulkNotificationTemplateId");

                    b.HasIndex("Status");

                    b.ToTable("BulkNotifications");
                });

            modelBuilder.Entity("Neo.BulkNotifications.Models.BulkNotificationTemplate", b =>
                {
                    b.Property<int>("BulkNotificationTemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BulkNotificationTemplateId"));

                    b.Property<string>("BulkNotificationTypeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CriteriaJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GridLayout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("BulkNotificationTemplateId");

                    b.HasIndex("TenantId");

                    b.ToTable("BulkNotificationTemplates");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.CustomTemplateLayout", b =>
                {
                    b.Property<int>("CustomTemplateLayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomTemplateLayoutId"));

                    b.Property<string>("CultureCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("LayoutContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StyleSheetId")
                        .HasColumnType("int");

                    b.Property<int>("TemplateLayoutId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("CustomTemplateLayoutId");

                    b.HasIndex("StyleSheetId");

                    b.HasIndex("TemplateLayoutId");

                    b.HasIndex("TenantId");

                    b.ToTable("CustomTemplateLayouts");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.FileAttachment", b =>
                {
                    b.Property<int>("FileAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileAttachmentId"));

                    b.Property<Guid>("FileDescriptorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("NotificationBatchId")
                        .HasColumnType("int");

                    b.HasKey("FileAttachmentId");

                    b.HasIndex("FileDescriptorId");

                    b.HasIndex("NotificationBatchId");

                    b.ToTable("FileAttachments");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.FileDescriptor", b =>
                {
                    b.Property<Guid>("FileDescriptorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("FileDataId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsExternal")
                        .HasColumnType("bit");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("FileDescriptorId");

                    b.ToTable("FileDescriptors");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<object>("Key")
                        .HasColumnType("sql_variant");

                    b.Property<int>("NotificationBatchId")
                        .HasColumnType("int");

                    b.Property<string>("PopupData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PopupStatus")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("NotificationBatchId");

                    b.HasIndex("PopupStatus");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.NotificationBatch", b =>
                {
                    b.Property<int>("NotificationBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationBatchId"));

                    b.Property<string>("PopupData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<int?>("TemplateTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("NotificationBatchId");

                    b.HasIndex("TemplateTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("NotificationBatches");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.NotificationSettings", b =>
                {
                    b.Property<int>("NotificationSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationSettingId"));

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("NotificationSettingId");

                    b.HasIndex("TenantId");

                    b.ToTable("NotificationSettings");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.StyleSheet", b =>
                {
                    b.Property<int>("StyleSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StyleSheetId"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StyleSheetBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StyleSheetName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("StyleSheetId");

                    b.HasIndex("TenantId");

                    b.ToTable("TemplateStyleSheets");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.Template", b =>
                {
                    b.Property<int>("TemplateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateId"));

                    b.Property<string>("CultureCode")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TemplateTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("TemplateId");

                    b.HasIndex("TenantId");

                    b.HasIndex("TemplateTypeId", "TenantId", "CultureCode", "RecordId")
                        .IsUnique();

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateLayout", b =>
                {
                    b.Property<int>("TemplateLayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateLayoutId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("LayoutContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutKey")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("LayoutName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("StyleSheetId")
                        .HasColumnType("int");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("TemplateLayoutId");

                    b.HasIndex("StyleSheetId");

                    b.HasIndex("TenantId");

                    b.ToTable("TemplateLayouts");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateLayoutOptions", b =>
                {
                    b.Property<int>("TemplateLayoutOptionsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateLayoutOptionsId"));

                    b.Property<int?>("DefaultTemplateLayoutId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("TemplateLayoutOptionsId");

                    b.HasIndex("DefaultTemplateLayoutId");

                    b.HasIndex("TenantId");

                    b.ToTable("TemplateLayoutOptions");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateType", b =>
                {
                    b.Property<int>("TemplateTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateTypeId"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DefaultPopupData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ExampleData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JsonSchema")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NotificationTypes")
                        .HasColumnType("int");

                    b.Property<int>("PersistType")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessorType")
                        .HasColumnType("int");

                    b.Property<bool>("SuppressLayout")
                        .HasColumnType("bit");

                    b.Property<int?>("TemplateLayoutId")
                        .HasColumnType("int");

                    b.Property<int?>("TemplatePriority")
                        .HasColumnType("int");

                    b.Property<string>("TemplateTypeKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TemplateTypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TemplateTypeId");

                    b.HasIndex("TemplateLayoutId");

                    b.HasIndex("TemplateTypeKey")
                        .IsUnique();

                    b.ToTable("TemplateTypes");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateTypeRecordSettings", b =>
                {
                    b.Property<int>("TemplateTypeRecordSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateTypeRecordSettingsId"));

                    b.Property<string>("RecordId")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("TemplateTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("TemplateTypeRecordSettingsId");

                    b.HasIndex("TemplateTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("TemplateTypeRecordSettings");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateTypeSettings", b =>
                {
                    b.Property<int>("TemplateTypeSettingsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TemplateTypeSettingsId"));

                    b.Property<int>("TemplateTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("TemplateTypeSettingsId");

                    b.HasIndex("TemplateTypeId");

                    b.HasIndex("TenantId");

                    b.ToTable("TemplateTypeSettings");
                });

            modelBuilder.Entity("Neo.BulkNotifications.Models.BulkNotification", b =>
                {
                    b.HasOne("Neo.BulkNotifications.Models.BulkNotificationTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("BulkNotificationTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BulkNotificationStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("BulkNotification_Status_BulkNotificationStatus");

                    b.OwnsOne("Neo.BulkNotifications.Models.BulkNotificationSendResult", "SendResult", b1 =>
                        {
                            b1.Property<int>("BulkNotificationId")
                                .HasColumnType("int");

                            b1.Property<int>("FailedCount")
                                .HasColumnType("int");

                            b1.Property<int?>("NotificationBatchId")
                                .HasColumnType("int");

                            b1.Property<int>("NotificationCount")
                                .HasColumnType("int");

                            b1.Property<int>("SentCount")
                                .HasColumnType("int");

                            b1.HasKey("BulkNotificationId");

                            b1.ToTable("BulkNotifications");

                            b1.WithOwner()
                                .HasForeignKey("BulkNotificationId");
                        });

                    b.Navigation("SendResult")
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("Neo.BulkNotifications.Models.BulkNotificationTemplate", b =>
                {
                    b.OwnsOne("Neo.Model.ValueObjects.AuditValues", "Audit", b1 =>
                        {
                            b1.Property<int>("BulkNotificationTemplateId")
                                .HasColumnType("int");

                            b1.Property<int>("CreatedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime");

                            b1.Property<int>("ModifiedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ModifiedOn")
                                .HasColumnType("datetime");

                            b1.HasKey("BulkNotificationTemplateId");

                            b1.ToTable("BulkNotificationTemplates");

                            b1.WithOwner()
                                .HasForeignKey("BulkNotificationTemplateId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.CustomTemplateLayout", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.StyleSheet", "StyleSheet")
                        .WithMany()
                        .HasForeignKey("StyleSheetId");

                    b.HasOne("Neo.NotificationServer.Models.TemplateLayout", "TemplateLayout")
                        .WithMany("CustomTemplateLayouts")
                        .HasForeignKey("TemplateLayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StyleSheet");

                    b.Navigation("TemplateLayout");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.FileAttachment", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.FileDescriptor", "FileDescriptor")
                        .WithMany()
                        .HasForeignKey("FileDescriptorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Neo.NotificationServer.Models.NotificationBatch", "NotificationBatch")
                        .WithMany("FileAttachments")
                        .HasForeignKey("NotificationBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDescriptor");

                    b.Navigation("NotificationBatch");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.Notification", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.NotificationBatch", null)
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeliveryStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("PopupStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("Notification_PopupStatus_DeliveryStatus");

                    b.OwnsOne("Neo.NotificationServer.Models.NotificationSendResult", "Email", b1 =>
                        {
                            b1.Property<int>("NotificationId")
                                .HasColumnType("int");

                            b1.Property<string>("Error")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Identifier")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("SentDate")
                                .HasColumnType("datetime");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<bool>("UsedOverrideRecipient")
                                .HasColumnType("bit");

                            b1.HasKey("NotificationId");

                            b1.HasIndex("Status")
                                .HasFilter("Email_Status = 1");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");

                            b1.HasOne("DeliveryStatusEntity", null)
                                .WithMany()
                                .HasForeignKey("Status")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("Email_Status_DeliveryStatus");
                        });

                    b.OwnsOne("Neo.NotificationServer.Models.TemplateDefinition", "Message", b1 =>
                        {
                            b1.Property<int>("NotificationId")
                                .HasColumnType("int");

                            b1.Property<string>("AppBody")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Body")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShortBody")
                                .HasMaxLength(918)
                                .HasColumnType("nvarchar(918)");

                            b1.Property<string>("Subject")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NotificationId");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");
                        });

                    b.OwnsOne("Neo.NotificationServer.Models.NotificationSendResult", "Sms", b1 =>
                        {
                            b1.Property<int>("NotificationId")
                                .HasColumnType("int");

                            b1.Property<string>("Error")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Identifier")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<DateTime?>("SentDate")
                                .HasColumnType("datetime");

                            b1.Property<int>("Status")
                                .HasColumnType("int");

                            b1.Property<bool>("UsedOverrideRecipient")
                                .HasColumnType("bit");

                            b1.HasKey("NotificationId");

                            b1.HasIndex("Status")
                                .HasFilter("Sms_Status = 1");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");

                            b1.HasOne("DeliveryStatusEntity", null)
                                .WithMany()
                                .HasForeignKey("Status")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired()
                                .HasConstraintName("Sms_Status_DeliveryStatus");
                        });

                    b.OwnsOne("Neo.NotificationServer.Models.Recipient", "Recipient", b1 =>
                        {
                            b1.Property<int>("NotificationId")
                                .HasColumnType("int");

                            b1.Property<string>("BCCEmailAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CCEmailAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("CellNumber")
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("EmailAddress")
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)");

                            b1.Property<Guid?>("RecipientUserId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("NotificationId");

                            b1.ToTable("Notifications");

                            b1.WithOwner()
                                .HasForeignKey("NotificationId");
                        });

                    b.Navigation("Email");

                    b.Navigation("Message");

                    b.Navigation("Recipient")
                        .IsRequired();

                    b.Navigation("Sms");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.NotificationBatch", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.TemplateType", null)
                        .WithMany()
                        .HasForeignKey("TemplateTypeId");

                    b.OwnsOne("Neo.NotificationServer.Models.LayoutInfo", "Layout", b1 =>
                        {
                            b1.Property<int>("NotificationBatchId")
                                .HasColumnType("int");

                            b1.Property<string>("OuterContent")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("StyleSheetId")
                                .HasColumnType("int");

                            b1.HasKey("NotificationBatchId");

                            b1.HasIndex("StyleSheetId");

                            b1.ToTable("NotificationBatches");

                            b1.WithOwner()
                                .HasForeignKey("NotificationBatchId");

                            b1.HasOne("Neo.NotificationServer.Models.StyleSheet", "StyleSheet")
                                .WithMany()
                                .HasForeignKey("StyleSheetId");

                            b1.Navigation("StyleSheet");
                        });

                    b.OwnsOne("Neo.Model.ValueObjects.AuditValues", "Audit", b1 =>
                        {
                            b1.Property<int>("NotificationBatchId")
                                .HasColumnType("int");

                            b1.Property<int>("CreatedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime");

                            b1.Property<int>("ModifiedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ModifiedOn")
                                .HasColumnType("datetime");

                            b1.HasKey("NotificationBatchId");

                            b1.ToTable("NotificationBatches");

                            b1.WithOwner()
                                .HasForeignKey("NotificationBatchId");
                        });

                    b.OwnsOne("Neo.NotificationServer.Models.Sender", "Sender", b1 =>
                        {
                            b1.Property<int>("NotificationBatchId")
                                .HasColumnType("int");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)");

                            b1.HasKey("NotificationBatchId");

                            b1.ToTable("NotificationBatches");

                            b1.WithOwner()
                                .HasForeignKey("NotificationBatchId");
                        });

                    b.OwnsOne("Neo.NotificationServer.Models.TemplateDefinition", "StaticMessage", b1 =>
                        {
                            b1.Property<int>("NotificationBatchId")
                                .HasColumnType("int");

                            b1.Property<string>("AppBody")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Body")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShortBody")
                                .HasMaxLength(918)
                                .HasColumnType("nvarchar(918)");

                            b1.Property<string>("Subject")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NotificationBatchId");

                            b1.ToTable("NotificationBatches");

                            b1.WithOwner()
                                .HasForeignKey("NotificationBatchId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Layout");

                    b.Navigation("Sender");

                    b.Navigation("StaticMessage");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.NotificationSettings", b =>
                {
                    b.OwnsOne("Neo.NotificationServer.Models.RecipientOverride", "EmailOverride", b1 =>
                        {
                            b1.Property<int>("NotificationSettingsNotificationSettingId")
                                .HasColumnType("int");

                            b1.Property<string>("AllowedList")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Default")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NotificationSettingsNotificationSettingId");

                            b1.ToTable("NotificationSettings");

                            b1.WithOwner()
                                .HasForeignKey("NotificationSettingsNotificationSettingId");
                        });

                    b.OwnsOne("Neo.NotificationServer.Models.Sender", "Sender", b1 =>
                        {
                            b1.Property<int>("NotificationSettingsNotificationSettingId")
                                .HasColumnType("int");

                            b1.Property<string>("DisplayName")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("EmailAddress")
                                .IsRequired()
                                .HasMaxLength(254)
                                .HasColumnType("nvarchar(254)");

                            b1.HasKey("NotificationSettingsNotificationSettingId");

                            b1.ToTable("NotificationSettings");

                            b1.WithOwner()
                                .HasForeignKey("NotificationSettingsNotificationSettingId");
                        });

                    b.OwnsOne("Neo.NotificationServer.Models.RecipientOverride", "SmsOverride", b1 =>
                        {
                            b1.Property<int>("NotificationSettingsNotificationSettingId")
                                .HasColumnType("int");

                            b1.Property<string>("AllowedList")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Default")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NotificationSettingsNotificationSettingId");

                            b1.ToTable("NotificationSettings");

                            b1.WithOwner()
                                .HasForeignKey("NotificationSettingsNotificationSettingId");
                        });

                    b.OwnsOne("Neo.NotificationServer.Models.SystemContacts", "SystemContacts", b1 =>
                        {
                            b1.Property<int>("NotificationSettingsNotificationSettingId")
                                .HasColumnType("int");

                            b1.Property<string>("ClientAdminEmailAddress")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("DeveloperEmailAddress")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("NotificationSettingsNotificationSettingId");

                            b1.ToTable("NotificationSettings");

                            b1.WithOwner()
                                .HasForeignKey("NotificationSettingsNotificationSettingId");
                        });

                    b.Navigation("EmailOverride");

                    b.Navigation("Sender");

                    b.Navigation("SmsOverride");

                    b.Navigation("SystemContacts");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.StyleSheet", b =>
                {
                    b.OwnsOne("Neo.Model.ValueObjects.AuditValues", "Audit", b1 =>
                        {
                            b1.Property<int>("StyleSheetId")
                                .HasColumnType("int");

                            b1.Property<int>("CreatedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime");

                            b1.Property<int>("ModifiedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ModifiedOn")
                                .HasColumnType("datetime");

                            b1.HasKey("StyleSheetId");

                            b1.ToTable("TemplateStyleSheets");

                            b1.WithOwner()
                                .HasForeignKey("StyleSheetId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.Template", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.TemplateType", null)
                        .WithMany("Templates")
                        .HasForeignKey("TemplateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Neo.Model.ValueObjects.AuditValues", "Audit", b1 =>
                        {
                            b1.Property<int>("TemplateId")
                                .HasColumnType("int");

                            b1.Property<int>("CreatedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime");

                            b1.Property<int>("ModifiedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ModifiedOn")
                                .HasColumnType("datetime");

                            b1.HasKey("TemplateId");

                            b1.ToTable("Templates");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");
                        });

                    b.OwnsOne("Neo.NotificationServer.Models.TemplateDefinition", "TemplateDefinition", b1 =>
                        {
                            b1.Property<int>("TemplateId")
                                .HasColumnType("int");

                            b1.Property<string>("AppBody")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Body")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShortBody")
                                .HasMaxLength(918)
                                .HasColumnType("nvarchar(918)");

                            b1.Property<string>("Subject")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TemplateId");

                            b1.ToTable("Templates");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("TemplateDefinition")
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateLayout", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.StyleSheet", "StyleSheet")
                        .WithMany()
                        .HasForeignKey("StyleSheetId");

                    b.OwnsOne("Neo.Model.ValueObjects.AuditValues", "Audit", b1 =>
                        {
                            b1.Property<int>("TemplateLayoutId")
                                .HasColumnType("int");

                            b1.Property<int>("CreatedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedOn")
                                .HasColumnType("datetime");

                            b1.Property<int>("ModifiedBy")
                                .HasColumnType("int");

                            b1.Property<DateTime>("ModifiedOn")
                                .HasColumnType("datetime");

                            b1.HasKey("TemplateLayoutId");

                            b1.ToTable("TemplateLayouts");

                            b1.WithOwner()
                                .HasForeignKey("TemplateLayoutId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("StyleSheet");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateLayoutOptions", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.TemplateLayout", "DefaultTemplateLayout")
                        .WithMany()
                        .HasForeignKey("DefaultTemplateLayoutId");

                    b.Navigation("DefaultTemplateLayout");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateType", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.TemplateLayout", "TemplateLayout")
                        .WithMany()
                        .HasForeignKey("TemplateLayoutId");

                    b.OwnsOne("Neo.NotificationServer.Models.TemplateDefinition", "DefaultTemplate", b1 =>
                        {
                            b1.Property<int>("TemplateTypeId")
                                .HasColumnType("int");

                            b1.Property<string>("AppBody")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Body")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("ShortBody")
                                .HasMaxLength(918)
                                .HasColumnType("nvarchar(918)");

                            b1.Property<string>("Subject")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("TemplateTypeId");

                            b1.ToTable("TemplateTypes");

                            b1.WithOwner()
                                .HasForeignKey("TemplateTypeId");
                        });

                    b.Navigation("DefaultTemplate")
                        .IsRequired();

                    b.Navigation("TemplateLayout");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateTypeRecordSettings", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.TemplateType", "TemplateType")
                        .WithMany()
                        .HasForeignKey("TemplateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Neo.NotificationServer.Models.TemplateTypeRecordSettingValues", "Values", b1 =>
                        {
                            b1.Property<int>("TemplateTypeRecordSettingsId")
                                .HasColumnType("int")
                                .HasColumnName("TemplateTypeRecordSettingsId");

                            b1.Property<int?>("TemplateLayoutId")
                                .HasColumnType("int")
                                .HasColumnName("TemplateLayoutId");

                            b1.HasKey("TemplateTypeRecordSettingsId");

                            b1.HasIndex("TemplateLayoutId");

                            b1.ToTable("TemplateTypeRecordSettings");

                            b1.HasOne("Neo.NotificationServer.Models.TemplateLayout", "TemplateLayout")
                                .WithMany()
                                .HasForeignKey("TemplateLayoutId");

                            b1.WithOwner()
                                .HasForeignKey("TemplateTypeRecordSettingsId");

                            b1.Navigation("TemplateLayout");
                        });

                    b.Navigation("TemplateType");

                    b.Navigation("Values")
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateTypeSettings", b =>
                {
                    b.HasOne("Neo.NotificationServer.Models.TemplateType", "TemplateType")
                        .WithMany()
                        .HasForeignKey("TemplateTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Neo.NotificationServer.Models.TemplateTypeSettingValues", "Values", b1 =>
                        {
                            b1.Property<int>("TemplateTypeSettingsId")
                                .HasColumnType("int")
                                .HasColumnName("TemplateTypeSettingsId");

                            b1.Property<int?>("SendType")
                                .HasColumnType("int")
                                .HasColumnName("SendType");

                            b1.Property<int?>("TemplateLayoutId")
                                .HasColumnType("int")
                                .HasColumnName("TemplateLayoutId");

                            b1.HasKey("TemplateTypeSettingsId");

                            b1.HasIndex("TemplateLayoutId");

                            b1.ToTable("TemplateTypeSettings");

                            b1.HasOne("Neo.NotificationServer.Models.TemplateLayout", "TemplateLayout")
                                .WithMany()
                                .HasForeignKey("TemplateLayoutId");

                            b1.WithOwner()
                                .HasForeignKey("TemplateTypeSettingsId");

                            b1.Navigation("TemplateLayout");
                        });

                    b.Navigation("TemplateType");

                    b.Navigation("Values")
                        .IsRequired();
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.NotificationBatch", b =>
                {
                    b.Navigation("FileAttachments");

                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateLayout", b =>
                {
                    b.Navigation("CustomTemplateLayouts");
                });

            modelBuilder.Entity("Neo.NotificationServer.Models.TemplateType", b =>
                {
                    b.Navigation("Templates");
                });
#pragma warning restore 612, 618
        }
    }
}
