{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "neo-web-app.serviceAccountName" . }}
  annotations:
    {{- if .Values.azureWorkLoadIdentity.enabled }}
    azure.workload.identity/client-id: {{ .Values.azureWorkLoadIdentity.clientId }}
    {{- end }}
  labels:
    {{- include "neo-web-app.labels" . | nindent 4 }}
    {{- if .Values.azureWorkLoadIdentity.enabled }}
    azure.workload.identity/use: "true"
    {{- end }}
{{- end }}