//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuckshop.IdentityServer.App {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DomainExceptions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DomainExceptions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tuckshop.IdentityServer.App.DomainExceptions", typeof(DomainExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already confirmed..
        /// </summary>
        public static string CannotPerformActionEmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("CannotPerformActionEmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user uses an external login provider..
        /// </summary>
        public static string CannotPerformActionForExternalLoginUsers {
            get {
                return ResourceManager.GetString("CannotPerformActionForExternalLoginUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA cannot be disabled because it is required for users using the {0} Identity Provider..
        /// </summary>
        public static string CannotPerformActionMFAIsRequired {
            get {
                return ResourceManager.GetString("CannotPerformActionMFAIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA is already enabled..
        /// </summary>
        public static string CannotPerformActionTwoFactorEnabled {
            get {
                return ResourceManager.GetString("CannotPerformActionTwoFactorEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MFA is already disabled..
        /// </summary>
        public static string CannotPerformActionTwoFactorNotEnabled {
            get {
                return ResourceManager.GetString("CannotPerformActionTwoFactorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already active..
        /// </summary>
        public static string CannotPerformActionUserAlreadyActive {
            get {
                return ResourceManager.GetString("CannotPerformActionUserAlreadyActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is already inactive..
        /// </summary>
        public static string CannotPerformActionUserAlreadyInactive {
            get {
                return ResourceManager.GetString("CannotPerformActionUserAlreadyInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is inactive, activate user first..
        /// </summary>
        public static string CannotPerformActionUserIsInactive {
            get {
                return ResourceManager.GetString("CannotPerformActionUserIsInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user is not locked..
        /// </summary>
        public static string CannotPerformActionUserIsNotLocked {
            get {
                return ResourceManager.GetString("CannotPerformActionUserIsNotLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has not configured their MFA..
        /// </summary>
        public static string CannotPerformActionUserMFANotConfigured {
            get {
                return ResourceManager.GetString("CannotPerformActionUserMFANotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user found for Id {0}..
        /// </summary>
        public static string NoUserFoundForId {
            get {
                return ResourceManager.GetString("NoUserFoundForId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot revoke invite, user has already registered..
        /// </summary>
        public static string UserInviteAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserInviteAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates of user invites not allowed..
        /// </summary>
        public static string UserInviteUpdateNotAllowed {
            get {
                return ResourceManager.GetString("UserInviteUpdateNotAllowed", resourceCulture);
            }
        }
    }
}
