// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tuckshop.Reporting;

#nullable disable

namespace Tuckshop.Reporting.Migrations.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20241010093218_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Neo.Reporting.Models.FileDescriptor", b =>
                {
                    b.Property<int>("FileDescriptorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileDescriptorId"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("FileDataId")
                        .HasColumnType("int");

                    b.Property<byte[]>("FileHash")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varbinary(32)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("FileDescriptorId");

                    b.ToTable("FileDescriptors");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportDataEntry", b =>
                {
                    b.Property<int>("ReportDataEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportDataEntryId"));

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ReportOperationId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("ReportDataEntryId");

                    b.HasIndex("ReportOperationId")
                        .IsUnique();

                    b.HasIndex("TenantId");

                    b.ToTable("ReportDataEntries");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportOperation", b =>
                {
                    b.Property<int>("ReportOperationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportOperationId"));

                    b.Property<DateTime?>("DataLoadCompletedOn")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataLoadStartedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("FailedOn")
                        .HasColumnType("datetime");

                    b.Property<int?>("FileDescriptorId")
                        .HasColumnType("int");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<int>("ReportRequestId")
                        .HasColumnType("int");

                    b.HasKey("ReportOperationId");

                    b.HasIndex("FileDescriptorId");

                    b.HasIndex("ReportRequestId");

                    b.ToTable("ReportOperations");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportRequest", b =>
                {
                    b.Property<int>("ReportRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportRequestId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Criteria")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DataLoadReportRequestId")
                        .HasColumnType("int");

                    b.Property<string>("ModelSchema")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("RequestDenied")
                        .HasColumnType("bit");

                    b.Property<int>("RequestType")
                        .HasMaxLength(50)
                        .HasColumnType("int");

                    b.Property<string>("RequestedByUserGuid")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime");

                    b.HasKey("ReportRequestId");

                    b.HasIndex("DataLoadReportRequestId");

                    b.HasIndex("RequestType");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId");

                    b.ToTable("ReportRequests");
                });

            modelBuilder.Entity("Neo.Reporting.Models.UserLayout", b =>
                {
                    b.Property<int>("UserLayoutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserLayoutId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime");

                    b.Property<string>("Layout")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PropertyKey")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReportKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserLayoutId");

                    b.ToTable("UserLayouts");
                });

            modelBuilder.Entity("ReportRequestStatusEntity", b =>
                {
                    b.Property<int>("ReportRequestStatusId")
                        .HasColumnType("int");

                    b.Property<string>("ReportRequestStatusName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReportRequestStatusId");

                    b.ToTable("ReportRequestStatuses");

                    b.HasData(
                        new
                        {
                            ReportRequestStatusId = 1,
                            ReportRequestStatusName = "Default"
                        },
                        new
                        {
                            ReportRequestStatusId = 2,
                            ReportRequestStatusName = "Request For Data"
                        },
                        new
                        {
                            ReportRequestStatusId = 30,
                            ReportRequestStatusName = "Data No Longer Available"
                        },
                        new
                        {
                            ReportRequestStatusId = 31,
                            ReportRequestStatusName = "Data Removed"
                        },
                        new
                        {
                            ReportRequestStatusId = 32,
                            ReportRequestStatusName = "Data Expired"
                        });
                });

            modelBuilder.Entity("ReportRequestTypeEntity", b =>
                {
                    b.Property<int>("ReportRequestTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ReportRequestTypeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ReportRequestTypeId");

                    b.ToTable("ReportRequestTypes");

                    b.HasData(
                        new
                        {
                            ReportRequestTypeId = 1,
                            ReportRequestTypeName = "View"
                        },
                        new
                        {
                            ReportRequestTypeId = 2,
                            ReportRequestTypeName = "View Data"
                        },
                        new
                        {
                            ReportRequestTypeId = 101,
                            ReportRequestTypeName = "Download Pdf"
                        },
                        new
                        {
                            ReportRequestTypeId = 102,
                            ReportRequestTypeName = "Download Excel"
                        },
                        new
                        {
                            ReportRequestTypeId = 110,
                            ReportRequestTypeName = "Download Grid Report Excel"
                        });
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportDataEntry", b =>
                {
                    b.HasOne("Neo.Reporting.Models.ReportOperation", "ReportOperation")
                        .WithMany()
                        .HasForeignKey("ReportOperationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportOperation");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportOperation", b =>
                {
                    b.HasOne("Neo.Reporting.Models.FileDescriptor", "FileDescriptor")
                        .WithMany()
                        .HasForeignKey("FileDescriptorId");

                    b.HasOne("Neo.Reporting.Models.ReportRequest", "ReportRequest")
                        .WithMany("ReportOperations")
                        .HasForeignKey("ReportRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileDescriptor");

                    b.Navigation("ReportRequest");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportRequest", b =>
                {
                    b.HasOne("Neo.Reporting.Models.ReportRequest", "DataLoadReportRequest")
                        .WithMany()
                        .HasForeignKey("DataLoadReportRequestId");

                    b.HasOne("ReportRequestTypeEntity", null)
                        .WithMany()
                        .HasForeignKey("RequestType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("ReportRequest_RequestType_ReportRequestType");

                    b.HasOne("ReportRequestStatusEntity", null)
                        .WithMany()
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("ReportRequest_Status_ReportRequestStatus");

                    b.Navigation("DataLoadReportRequest");
                });

            modelBuilder.Entity("Neo.Reporting.Models.ReportRequest", b =>
                {
                    b.Navigation("ReportOperations");
                });
#pragma warning restore 612, 618
        }
    }
}
