        location /${environment_prefix}/${path} {
                if ($http_neoauth != "${nginx_proxy_api_key}") {
                        return 401;
                }

                proxy_ssl_server_name ${proxy_ssl_server_name};
                ${proxy_headers}

                proxy_pass ${proxy_url};
        }