// <auto-generated />
// This file was generated using Add Scaffolded Item
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Neo.IdentityServer.Providers;

namespace Tuckshop.IdentityServer.Areas.Identity.Pages.Account
{
  [AllowAnonymous]
  public class ForgotPasswordConfirmation : PageModel
  {
    private readonly IDataProtectionOptionsProvider dataProtectionOptionsProvider;

    public ForgotPasswordConfirmation(IDataProtectionOptionsProvider dataProtectionOptionsProvider)
    {
      this.dataProtectionOptionsProvider = dataProtectionOptionsProvider;
    }

    /// <summary>
    /// Gets the link expiry hours.
    /// </summary>
    public string LinkExpiryDuration { get; private set; }

    public void OnGet()
    {
      if (this.dataProtectionOptionsProvider.GetOptions("ResetPassword").TokenLifespan.TotalHours > 1)
      {
        this.LinkExpiryDuration = $"{this.dataProtectionOptionsProvider.GetOptions("ResetPassword").TokenLifespan.TotalHours} hours";
      }
      else
      {
        this.LinkExpiryDuration = $"{this.dataProtectionOptionsProvider.GetOptions("ResetPassword").TokenLifespan.TotalMinutes} minutes";
      }
    }
  }
}
