// <auto-generated />
// This file was generated using Add Scaffolded Item
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.Extensions.Hosting;
using Neo.Extensions;
using Neo.IdentityServer.App.Services;
using Neo.IdentityServer.App.Services.IdentityProviders;
using Neo.IdentityServer.Models.IdentityProviders;
using Neo.IdentityServer.Models.SignIn;
using Neo.Model.Exceptions;
using Neo.Model.ValueObjects;
using Neo.NotificationServer.Services;
using Tuckshop.IdentityServer.App.Services;
using Tuckshop.IdentityServer.Contracts.Registration;
using Tuckshop.IdentityServer.Models;
using System.Text.Json.Serialization;

namespace Tuckshop.IdentityServer.Areas.Identity.Pages.Account
{
  [AllowAnonymous]
  public class RegisterModel : AccountPasswordPageModelBase<RegisterModel>
  {
    private const string UserAgent = "User-Agent";
    private readonly ILogger<RegisterModel> logger;
    private readonly IEmailSender emailSender;
    private readonly IRegistrationService registrationService;
    private readonly INotificationService notificationService;
    private readonly ISignInAuditService signInAuditService;
    private readonly IHostEnvironment environment;
    private readonly IIdentityProviderLookupService identityProviderService;

    public RegisterModel(
        ILogger<RegisterModel> logger,
        IEmailSender emailSender,
        IRegistrationService registrationService,
        INotificationService notificationService,
        ISignInAuditService signInAuditService,
        IUrlProvider urlProvider,
        IConfiguration configuration,
        IHostEnvironment environment,
        IIdentityProviderLookupService identityProviderService,
        IPasswordValidator<TuckshopApplicationUser> passwordValidator,
        UserManager<TuckshopApplicationUser> userManager)
      : base(logger, urlProvider, configuration, passwordValidator, userManager)
    {
      this.logger = logger;
      this.emailSender = emailSender;
      this.registrationService = registrationService;
      this.notificationService = notificationService;
      this.signInAuditService = signInAuditService;
      this.environment = environment;
      this.identityProviderService = identityProviderService;
    }

    [BindProperty]
    public InputModel Input { get; set; }

    public string ReturnUrl { get; set; }

    public class InputModel : IRegistrationUser
    {
      [Required]
      [EmailAddress]
      [Display(Name = "Email")]
      public string Email { get; set; }

      [Required]
      [Display(Name = "First Name")]
      public string FirstName { get; set; }

      [Required]
      [Display(Name = "Last Name")]
      public string LastName { get; set; }

      // Will come from parent RegisterModel (implemented via AccountPasswordPageModelBase)
      public string Password { get; set; }

      [JsonIgnore]
      public bool EmailConfirmed { get; set; }
    }

    public void OnGet(string returnUrl = null)
    {
      ReturnUrl = returnUrl;
    }

    private static HashSet<string> VerifiedParticipantIds = new HashSet<string>() { "00000002-000A-000B-0000-000000000001", "00000002-000A-000B-0000-000000000002" };

    public async Task<IActionResult> OnPostAsync(string returnUrl = null)
    {
      returnUrl = returnUrl ?? Url.Content("~/");
      if (ModelState.IsValid)
      {
        this.Input.Password = this.Password;

        var identityProvider = (await this.identityProviderService.GetIdentityProvidersAsync((int)IdentityProviderType.LoginCredentials)).First();

        try
        {
          var registerResult = await this.registrationService.RegisterUserAsync(this.Input, identityProvider.IdentityProviderId);

          if (registerResult.Success)
          {
            logger.LogDebug("User created a new account with password.");

            switch (registerResult.Type)
            {
              case RegisterResultType.PendingEmailVerification:
                return RedirectToPage("./RegisterConfirmation", new { emailConfirmation = true });
              case RegisterResultType.ConfigureMFA:
                await LogSignIn(registerResult);
                return this.RedirectToPage("./EnableAuthenticator", new { returnUrl = ReturnUrl });
              case RegisterResultType.RequiresMFA:
                return this.RedirectToPage("./LoginWith2Fa", new { returnUrl = ReturnUrl });
              case RegisterResultType.SignedIn:
                await LogSignIn(registerResult);
                return this.AuthenticatedRedirect(returnUrl);
            }
          }
          else
          {
            ModelState.AddModelError(string.Empty, registerResult.FailureReason);
            this.Logger.LogInformation($"Cannot register: {registerResult.FailureReason}");
          }
        }
        catch (InvalidDomainOperationException domainException)
        {
          ModelState.AddModelError(string.Empty, domainException.Message);
          this.Logger.LogInformation($"Failed registration: {domainException.Message}");
        }
        catch (Exception ex)
        {
          ModelState.AddModelError(string.Empty, $"Error during registration, please contact the System Administrator");
          this.logger.LogError(ex, "Error during registration");
        }
      }

      // If we got this far, something failed, redisplay form
      return Page();
    }

    private async Task LogSignIn(RegisterResult registerResult)
    {
      var requestHeaderDetails = RequestHeaderDetails.Create(
          this.HttpContext.Request.Headers[UserAgent],
          this.HttpContext.Connection?.RemoteIpAddress?.ToString() ?? string.Empty);

      var identityProvider = (await this.identityProviderService.GetIdentityProvidersAsync((int)IdentityProviderType.LoginCredentials)).First();
      this.signInAuditService.LogSignIn(SignInAudit.SuccessSignInAudit(registerResult.User.Id, identityProvider.IdentityProviderId, $"Registration Sign In: {registerResult.Type.Description()}", requestHeaderDetails));
    }
  }
}