// <auto-generated />
// This file was generated using Add Scaffolded Item
// <auto-generated />
// This file was generated using Add Scaffolded Item
using Neo.IdentityServer.Services;

namespace Tuckshop.IdentityServer.Areas.Identity.Pages.Account
{
  using Microsoft.AspNetCore.Authorization;
  using Microsoft.AspNetCore.Mvc.RazorPages;
  using Neo.IdentityServer.Providers;

  /// <summary>
  /// SuccessfulRegistationModel.
  /// </summary>
  [AllowAnonymous]
  public class RegisterConfirmationModel : PageModel
  {
    private readonly IDataProtectionOptionsProvider dataProtectionOptionsProvider;

    public RegisterConfirmationModel(IDataProtectionOptionsProvider dataProtectionOptionsProvider)
    {
      this.dataProtectionOptionsProvider = dataProtectionOptionsProvider;
    }

    /// <summary>
    /// Gets a value indicating whether an email was sent or not
    /// </summary>
    public bool EmailConfirmation { get; private set; }

    /// <summary>
    /// Gets or sets the home page url.
    /// </summary>
    public string ReturnUrl { get; set; }

    /// <summary>
    /// Gets the link expiry hours.
    /// </summary>
    public double LinkExpiryHours { get; private set; }

    public void OnGet(bool emailConfirmation, bool isAdmin, string returnUrl = null)
    {
      this.EmailConfirmation = emailConfirmation;
      this.ReturnUrl = returnUrl ?? Url.Content("~/");
      this.LinkExpiryHours = this.dataProtectionOptionsProvider.GetOptions("EmailConfirmation").TokenLifespan.TotalHours;
    }
  }
}