// <auto-generated />
// This file was generated using Add Scaffolded Item
namespace Tuckshop.IdentityServer.Areas.Identity.Pages.Account
{
  using Microsoft.AspNetCore.Authorization;
  using Microsoft.AspNetCore.Identity;
  using Microsoft.AspNetCore.Mvc;
  using Microsoft.AspNetCore.Mvc.RazorPages;
  using System.ComponentModel.DataAnnotations;
  using System.Threading.Tasks;
  using Tuckshop.IdentityServer.Models;
  using Tuckshop.IdentityServer.App.Services;

  [AllowAnonymous]
  public class ResetPasswordModel : AccountPasswordPageModelBase<ResetPasswordModel>
  {
    private readonly UserManager<TuckshopApplicationUser> userManager;

    public ResetPasswordModel(
        ILogger<ResetPasswordModel> logger,
        IUrlProvider urlProvider,
        IConfiguration configuration,
        IPasswordValidator<TuckshopApplicationUser> passwordValidator,
        UserManager<TuckshopApplicationUser> userManager)
      : base(logger, urlProvider, configuration, passwordValidator, userManager)
    {
      this.userManager = userManager;
    }

    [BindProperty]
    public InputModel Input { get; set; }

    public class InputModel
    {
      [Required]
      [EmailAddress]
      public string Email { get; set; }

      // Will come from parent RegisterModel (implemented via AccountPasswordPageModelBase)
      public string Password { get; set; }

      public string Code { get; set; }
    }

    public IActionResult OnGet(string code = null)
    {
      if (code == null)
      {
        return BadRequest("A code must be supplied for password reset.");
      }
      else
      {
        Input = new InputModel
        {
          Code = code, 
        };
        return Page();
      }
    }

    public async Task<IActionResult> OnPostAsync()
    {
      if (!ModelState.IsValid)
      {
        return Page();
      }

      this.Input.Password = this.Password;

      var user = await userManager.FindByEmailAsync(Input.Email);
      if (user == null)
      {
        // Don't reveal that the user does not exist
        return RedirectToPage("./ResetPasswordConfirmation");
      }

      var result = await userManager.ResetPasswordAsync(user, Input.Code, Input.Password);
      if (result.Succeeded)
      {
        return RedirectToPage("./ResetPasswordConfirmation");
      }

      foreach (var error in result.Errors)
      {
        ModelState.AddModelError(string.Empty, error.Description);
      }
      return Page();
    }
  }
}
