# This is the default nginx configuration for the web app. 
# It is possible to override the configuration for a specific environment by making a copy of this file, 
# and renaming it to `nginx.{env}.conf`, where `{env}` is the value of `config.Environment` in your application yaml file. (E.g. nginx.prd.conf). 
# When the web-app starts up, it will first check for the presence of an environment specific configuration file before falling back to the default configuration. 
# You can check the application logs to confirm that the correct file is being loaded.
server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    location ~ ^/$ {
        rewrite  ^.*$  /index.html  last;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # Security Headers
    add_header X-Frame-Options "SAMEORIGIN";
    add_header Content-Security-Policy "frame-ancestors 'self'";
    add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin";
    add_header Permissions-Policy "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()";
    add_header Content-Security-Policy-Report-Only "upgrade-insecure-requests";
}
